name: webapp
description: "YakushiinL2S. Convert Dual Language Lrc To Srt For YakushiinPlayer."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  bot_toast: ^4.1.3
  dio: ^5.8.0+1
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.5.3
  adaptive_theme: ^3.7.0
  flutter_smart_dialog: ^4.9.8+8
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  code_text_field: ^1.1.0
  flutter_riverpod: ^2.6.1
  file_picker: ^10.2.0
  web: ^1.1.1
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  fonts:
    - family: LXGWWenKai
      fonts:
        - asset: lib/theme/fonts/LXGWWenKai/LXGWWenKai-Medium.ttf
          weight: 500
        - asset: lib/theme/fonts/LXGWWenKai/LXGWWenKai-Regular.ttf
          weight: 400
        - asset: lib/theme/fonts/LXGWWenKai/LXGWWenKai-Light.ttf
          weight: 300